/*********************************************************************
 * This file is a part of FItsSec2 project: Implementation of 
 * IEEE Std. 1609.2,
 * ETSI TS 103 097 v1.3.1,
 * ETSI TS 102 941 v1.3.1
 * Copyright (C) 2020  Denis Filatov (denis.filatov()fillabs.com)

 * This file is NOT a free or open source software and shall not me used
 * in any way not explicitly authorized by the author.
*********************************************************************/

#ifndef fitsec_error_h
#define fitsec_error_h

#include <errno.h>

#define FSISERR(X) ((0x1F&(X))?1:0)
#define FSISOK(X)  ((0x1F&(X))?0:1)

// events (0..32)
#define FSERR_OK		      0x0
#define FSERR_NOT_IMPLEMENTED EACCES
#define FSERR_PARSEERROR	  EFAULT
#define FSERR_NOSPACE		  ENOSPC
#define FSERR_INVALID		  EINVAL
#define FSERR_UNKNOWN		  ENOENT
#define FSERR_UNTRUSTED		  ENODEV
#define FSERR_ORDER		      EBADF
#define FSERR_NOT_YET_VALID   E2BIG
#define FSERR_UNSUPPORTED     ENOTTY
#define FSERR_EVAL_EXPIRED    ERANGE

#define _FSERR_SIZEOF 32

// elementes
#define FSERR_ELEMENTS_SHIFT 5
enum {
    _FSERR_NOT_IMPLEMENTED = 0,
    _FSERR_EL_VERSION,
    _FSERR_EL_SIZE,
    _FSERR_EL_TYPE,
    _FSERR_EL_DIGEST,
    _FSERR_EL_AID,
	_FSERR_EL_SSP,
	_FSERR_EL_PK_ALGORITHM,
    _FSERR_EL_SYM_ALGORITHM,
    _FSERR_EL_NAME,
    _FSERR_EL_ASSURANCE_LEVEL,
	_FSERR_EL_TIME,
    _FSERR_EL_START_TIME,
    _FSERR_EL_END_TIME,
	_FSERR_EL_DURATION,
    _FSERR_EL_PUBLIC_KEY,
    _FSERR_EL_RECONSTRUCTION_VALUE,
    _FSERR_EL_P2P_CERTIFICATE_REQUEST,
    _FSERR_EL_LOCATION,
    _FSERR_EL_LATITUDE,
    _FSERR_EL_LONGITUDE,
    _FSERR_EL_ECC_POINT,
//    _FSERR_EL_ECC_RADIUS,
    _FSERR_EL_ROOT,
    _FSERR_EL_HASH,
    _FSERR_EL_MAC,
    _FSERR_EL_CONTRIBUTOR,
    _FSERR_EL_ID,
    _FSERR_EL_CRL_REQUEST,
    _FSERR_EL_CTL_REQUEST,
    _FSERR_EL_FITSEC_EXT
};

#define FSERR_VERSION                 (_FSERR_EL_VERSION<<FSERR_ELEMENTS_SHIFT)
#define FSERR_SIZE                    (_FSERR_EL_SIZE<<FSERR_ELEMENTS_SHIFT)
#define FSERR_TYPE                    (_FSERR_EL_TYPE<<FSERR_ELEMENTS_SHIFT)
#define FSERR_DIGEST                  (_FSERR_EL_DIGEST<<FSERR_ELEMENTS_SHIFT)
#define FSERR_AID                     (_FSERR_EL_AID<<FSERR_ELEMENTS_SHIFT)
#define FSERR_SSP                     (_FSERR_EL_SSP<<FSERR_ELEMENTS_SHIFT)
#define FSERR_PK_ALGORITHM            (_FSERR_EL_PK_ALGORITHM<<FSERR_ELEMENTS_SHIFT)
#define FSERR_SYM_ALGORITHM           (_FSERR_EL_SYM_ALGORITHM<<FSERR_ELEMENTS_SHIFT)
#define FSERR_NAME                    (_FSERR_EL_NAME<<FSERR_ELEMENTS_SHIFT)
#define FSERR_ASSURANCE_LEVEL         (_FSERR_EL_ASSURANCE_LEVEL<<FSERR_ELEMENTS_SHIFT)
#define FSERR_TIME                    (_FSERR_EL_TIME<<FSERR_ELEMENTS_SHIFT)
#define FSERR_START_TIME              (_FSERR_EL_START_TIME<<FSERR_ELEMENTS_SHIFT)
#define FSERR_END_TIME                (_FSERR_EL_END_TIME<<FSERR_ELEMENTS_SHIFT)
#define FSERR_DURATION                (_FSERR_EL_DURATION<<FSERR_ELEMENTS_SHIFT)
#define FSERR_PUBLIC_KEY              (_FSERR_EL_PUBLIC_KEY<<FSERR_ELEMENTS_SHIFT)
#define FSERR_RECONSTRUCTION_VALUE    (_FSERR_EL_RECONSTRUCTION_VALUE<<FSERR_ELEMENTS_SHIFT)
#define FSERR_P2P_CERTIFICATE_REQUEST (_FSERR_EL_P2P_CERTIFICATE_REQUEST<<FSERR_ELEMENTS_SHIFT)
#define FSERR_LOCATION                (_FSERR_EL_LOCATION<<FSERR_ELEMENTS_SHIFT)
#define FSERR_LATITUDE                (_FSERR_EL_LATITUDE<<FSERR_ELEMENTS_SHIFT)
#define FSERR_LONGITUDE               (_FSERR_EL_LONGITUDE<<FSERR_ELEMENTS_SHIFT)
#define FSERR_ECC_POINT               (_FSERR_EL_ECC_POINT<<FSERR_ELEMENTS_SHIFT)
#define FSERR_ECC_RADIUS              (_FSERR_EL_ECC_RADIUS<<FSERR_ELEMENTS_SHIFT)
#define FSERR_ROOT                    (_FSERR_EL_ROOT<<FSERR_ELEMENTS_SHIFT)
#define FSERR_HASH                    (_FSERR_EL_HASH<<FSERR_ELEMENTS_SHIFT)
#define FSERR_MAC                     (_FSERR_EL_MAC<<FSERR_ELEMENTS_SHIFT)
#define FSERR_CONTRIBUTOR             (_FSERR_EL_CONTRIBUTOR<<FSERR_ELEMENTS_SHIFT)
#define FSERR_ID                      (_FSERR_EL_ID<<FSERR_ELEMENTS_SHIFT)
#define FSERR_CRL_REQUEST             (_FSERR_EL_CRL_REQUEST<<FSERR_ELEMENTS_SHIFT)
#define FSERR_CTL_REQUEST             (_FSERR_EL_CTL_REQUEST<<FSERR_ELEMENTS_SHIFT)
#define FSERR_FITSEC_EXT              (_FSERR_EL_FITSEC_EXT<<FSERR_ELEMENTS_SHIFT)

// containers
// starts from the last bit of the error 
enum {
    _FSERR_EL_NONE = 0,
    _FSERR_EL_MESSAGE,
    _FSERR_EL_P2P,
    _FSERR_EL_CRL,
    _FSERR_EL_CTL,
    _FSERR_EL_CERTIFICATE,
	_FSERR_EL_SIGNER,
	_FSERR_EL_PAYLOAD,
	_FSERR_EL_SIGNATURE,
	_FSERR_EL_VALIDITY_RESTRICTION,
	_FSERR_EL_APP_PERMISSIONS,
	_FSERR_EL_ISSUE_PERMISSIONS,
    _FSERR_EL_RECIPIENT_INFO,
	_FSERR_EL_REGION,
	_FSERR_EL_IDENTIFIED,
    _FSERR_EL_CIRCLE,
    _FSERR_EL_POLYGON,
    _FSERR_EL_RECTANGLE,
    _FSERR_EL_VERIFICATION_KEY,
    _FSERR_EL_ENCRYPTION_KEY,
    _FSERR_EL_ENC_PARAMETERS,
    _FSERR_EL_EXTENSION,
    _FSERR_EL_DC,

    _FSERR_EL_MAX_VALUE,
};

#define FSERR_CONTAINER(N)  _FSERR_EL_##N
#define FSERR_CONTAINER_BIT(N)  (1<<( _FSERR_SIZEOF - FSERR_CONTAINER(N)))

#define FSERR_ENCRYPTED_KEY             FSERR_CONTAINER_BIT(ENCRYPTED_KEY)
#define FSERR_RECIPIENT_INFO			FSERR_CONTAINER_BIT(RECIPIENT_INFO)
#define FSERR_ENC_PARAMETERS            FSERR_CONTAINER_BIT(ENC_PARAMETERS)
#define FSERR_IDENTIFIED                FSERR_CONTAINER_BIT(IDENTIFIED)
#define FSERR_CIRCLE                    FSERR_CONTAINER_BIT(CIRCLE)
#define FSERR_POLYGON                   FSERR_CONTAINER_BIT(POLYGON)
#define FSERR_RECTANGLE                 FSERR_CONTAINER_BIT(RECTANGLE)
#define FSERR_REGION                    FSERR_CONTAINER_BIT(REGION)
#define FSERR_SIGNER					FSERR_CONTAINER_BIT(SIGNER)
#define FSERR_MESSAGE                   FSERR_CONTAINER_BIT(MESSAGE)
#define FSERR_P2P                       FSERR_CONTAINER_BIT(P2P)
#define FSERR_VALIDITY_RESTRICTION		FSERR_CONTAINER_BIT(VALIDITY_RESTRICTION)
#define FSERR_APP_PERMISSIONS			FSERR_CONTAINER_BIT(APP_PERMISSIONS)
#define FSERR_ISSUE_PERMISSIONS			FSERR_CONTAINER_BIT(ISSUE_PERMISSIONS)
#define FSERR_SIGNATURE					FSERR_CONTAINER_BIT(SIGNATURE)
#define FSERR_PAYLOAD					FSERR_CONTAINER_BIT(PAYLOAD)
#define FSERR_CERTIFICATE				FSERR_CONTAINER_BIT(CERTIFICATE)
#define FSERR_VERIFICATION_KEY          FSERR_CONTAINER_BIT(VERIFICATION_KEY)
#define FSERR_ENCRYPTION_KEY            FSERR_CONTAINER_BIT(ENCRYPTION_KEY)
#define FSERR_EXTENSION                 FSERR_CONTAINER_BIT(EXTENSION)
#define FSERR_CRL                       FSERR_CONTAINER_BIT(CRL)
#define FSERR_CTL                       FSERR_CONTAINER_BIT(CTL)
#define FSERR_DC                        FSERR_CONTAINER_BIT(DC)

#define FSERR_CONTAINERS_SHIFT (_FSERR_SIZEOF-_FSERR_EL_MAX_VALUE)

#define FSERR_ELEMENT(err) ((err & (-1 >> FSERR_CONTAINERS_SHIFT))>>FSERR_ELEMENTS_SHIFT)
//#define FSERR_SET_ELEMENT(E,e) (((E) & (((-1)<<FSERR_CONTAINERS_SHIFT) | ((1<<FSERR_ELEMENTS_SHIFT)-1))) | (e))
#define FSERR_ERROR(err)   ((err)  & ((1<<(FSERR_ELEMENTS_SHIFT))-1))
#define FSERR_IS_ELEMENT(err, elem) ((elem) == ((err) & (elem)))
#endif
